import { expect, test } from '@playwright/test'

test('keeps the header fixed while the crafting sheet opens and closes', async ({ page }) => {
  await page.goto('/')
  const header = page.locator('.app-header')
  const initialTop = await header.evaluate((element) => element.getBoundingClientRect().top)

  await page.getByRole('button', { name: /english.*search crafts/ }).click()
  await expect(page.getByRole('button', { name: 'Back to english (us) crafts' })).toBeVisible()
  expect(await header.evaluate((element) => element.getBoundingClientRect().top)).toBeCloseTo(initialTop, 0)

  await page.getByRole('button', { name: 'Back to english (us) crafts' }).click()
  await expect(page.getByRole('region', { name: 'Languages' })).toBeVisible()
  expect(await header.evaluate((element) => element.getBoundingClientRect().top)).toBeCloseTo(initialTop, 0)
})

test('expands a sheet item set without clipping its controls inside a compact row', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /english.*search crafts/ }).waitFor()
  await page.evaluate(() => {
    const workspace = JSON.parse(localStorage.getItem('mcsr.target-workspace.v1')!)
    const source = workspace.entries[0]
    workspace.entries = Array.from({ length: 18 }, (_, index) => ({ ...source, id: `expanded-${index}`, order: index }))
    localStorage.setItem('mcsr.target-workspace.v1', JSON.stringify(workspace))
  })
  await page.reload()
  await page.getByRole('button', { name: /english.*search crafts/ }).click()
  const entry = page.getByRole('region', { name: 'item set 1', exact: true })

  await entry.getByRole('button', { name: 'Expand item set 1' }).click()
  await expect(entry.getByRole('button', { name: /choose craft for/ }).first()).toBeVisible()
  expect(await entry.evaluate((element) => element.scrollHeight <= element.clientHeight + 1)).toBe(true)
})

test('crafting sheet customizes bed and anchor, persists choices, and fits narrow screens', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /english.*search crafts/ }).waitFor()
  // Reuse the starter inventory, keeping exactly the two targets in this example.
  await page.evaluate(() => {
    const workspace = JSON.parse(localStorage.getItem('mcsr.target-workspace.v1')!)
    const entry = workspace.entries.find((value: { targetIds: string[] }) => value.targetIds.includes('minecraft:respawn_anchor'))
    entry.targetIds = ['minecraft:white_bed', 'minecraft:respawn_anchor']
    entry.order = 0
    workspace.entries = [entry]
    localStorage.setItem('mcsr.target-workspace.v1', JSON.stringify(workspace))
  })
  await page.reload()
  await page.getByRole('button', { name: /english.*search crafts/ }).click()
  const sheet = page.locator('.crafting-sheet')
  const card = sheet.getByRole('region', { name: 'item set 1', exact: true })
  await expect(card.getByText('Calculating crafts…')).toHaveCount(0)
  await card.getByRole('button', { name: 'Expand item set 1' }).click()
  await expect(card.locator('.crafting-sheet__plan')).toContainText('aw')
  const initialSequence = await card.locator('.crafting-sheet__plan').textContent()
  await expect(card.getByRole('button', { name: 'combined craft', exact: true })).toHaveCount(0)
  await expect(card.getByRole('button', { name: 'individual items', exact: true })).toHaveCount(0)
  if (await card.getByRole('button', { name: 'Move White Bed up' }).isEnabled()) await card.getByRole('button', { name: 'Move White Bed up' }).click()
  await card.getByRole('button', { name: 'choose craft for White Bed' }).click()
  const bedChoices = card.getByRole('region', { name: 'Calculated crafts for White Bed' })
  await bedChoices.getByRole('searchbox').fill('bed')
  await bedChoices.getByRole('button', { name: /^bed 3 chars/ }).click()
  await card.getByRole('button', { name: 'choose craft for Respawn Anchor' }).click()
  const anchorChoices = card.getByRole('region', { name: 'Calculated crafts for Respawn Anchor' })
  await anchorChoices.getByRole('searchbox').fill('aw')
  await anchorChoices.getByRole('button', { name: /^aw 2 chars/ }).click()
  await expect(card.locator('.crafting-sheet__plan')).toHaveText(/your sequencebedSHaw/)
  await expect(sheet.getByLabel('Total characters')).toHaveText('5')
  await expect(sheet.getByLabel('Selected characters')).toHaveText('abdew')
  await expect(card.locator('.crafting-sheet__entry-metrics')).toContainText('+1 score')
  await page.reload()
  await page.getByRole('button', { name: /english.*search crafts/ }).click()
  await expect(card.getByLabel('Selected query for White Bed')).toHaveText('bed')
  await card.getByRole('button', { name: 'Expand item set 1' }).click()
  await expect(card.locator('.crafting-sheet__plan')).toHaveText(/your sequencebedSHaw/)

  await page.evaluate(() => document.fonts.ready)
  const fonts = await sheet.evaluate((element) => ({
    query: getComputedStyle(element.querySelector('.crafting-sheet__query-text')!).fontFamily,
    metric: getComputedStyle(element.querySelector('.crafting-sheet__totals strong')!).fontFamily,
    key: getComputedStyle(element.querySelector('.crafting-sheet__key')!).fontFamily,
    title: getComputedStyle(element.querySelector('.crafting-sheet__title')!).fontFamily,
    subtitle: getComputedStyle(element.querySelector('.crafting-sheet__toggle-label')!).fontFamily,
  }))
  expect(fonts.query).toContain('Monocraft')
  expect(fonts.title).toContain('Coiny')
  expect(fonts.subtitle).toContain('Coiny')
  for (const font of [fonts.metric, fonts.key, fonts.title]) expect(font).not.toContain('Monocraft')

  await sheet.screenshot({ path: 'test-results/crafting-sheet-desktop.png' })
  for (const width of [320, 375, 768]) {
    await page.setViewportSize({ width, height: 1000 })
    await card.getByRole('button', { name: 'choose craft for White Bed' }).click()
    await expect(card.getByRole('searchbox')).toBeVisible()
    expect(await sheet.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
    expect(await card.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
    await card.getByRole('searchbox').press('Escape')
  }
  await page.setViewportSize({ width: 375, height: 1000 })
  await sheet.screenshot({ path: 'test-results/crafting-sheet-mobile.png', style: '.app-header { visibility: hidden !important; }' })
  await card.getByRole('checkbox', { name: 'Include item set 1' }).uncheck()
  await expect(card.getByRole('button', { name: /item set 1/ })).toHaveCount(0)
  await expect(sheet.getByLabel('Total characters')).toHaveText('0')
  await sheet.getByRole('button', { name: 'reset sheet' }).click()
  await expect(card.getByRole('checkbox', { name: 'Include item set 1' })).toBeChecked()
  await expect(card.locator('.crafting-sheet__plan')).toHaveText(initialSequence!)
})

test('crafting sheet has compact rows and animates open and closed like calculated rows', async ({ page }) => {
  await page.goto('/')
  const sheet = page.locator('.crafting-sheet')
  const toggle = sheet.getByRole('button', { name: /english.*search crafts/ })
  await toggle.click()
  const panel = sheet.locator(':scope > .crafting-sheet__details')
  await expect(panel).toHaveCSS('animation-name', 'craft-disclosure-open')
  await expect(panel).toHaveCSS('animation-duration', '0.42s')
  const card = sheet.getByRole('region', { name: 'item set 1', exact: true })
  await expect(card.getByRole('button', { name: 'Expand item set 1' })).toBeVisible()
  await expect(card.locator('.crafting-sheet__query-preview')).toBeVisible()
  await expect(card.locator('.crafting-sheet__query-preview')).toHaveCSS('border-top-width', '1px')
  await expect(card.locator('.item-icon').first()).toHaveCSS('width', '24px')
  await expect(card.locator('.item-icon').first()).toHaveCSS('height', '24px')
  await expect(sheet.locator('.crafting-sheet__entry-body')).toHaveCount(0)
  await expect(sheet.getByText('Updating crafting sheet… Totals include ready crafts.')).toHaveCount(0)
  await page.evaluate(() => document.fonts.ready)
  await sheet.screenshot({ path: 'test-results/crafting-sheet-compact-desktop.png', style: '.app-header { visibility: hidden !important; }' })
  const headerTop = await card.evaluate((element) => element.getBoundingClientRect().top + window.scrollY)
  await card.getByRole('button', { name: 'Expand item set 1' }).click()
  const details = card.locator('.crafting-sheet__details')
  await expect(card.getByRole('button', { name: /choose craft for/ })).toBeVisible()
  await expect(details).toHaveCSS('animation-name', 'craft-disclosure-open')
  await card.getByRole('button', { name: 'Collapse item set 1' }).click()
  await expect(details).toHaveCSS('animation-name', 'craft-disclosure-close')
  await expect(details).toHaveAttribute('inert', '')
  await expect.poll(async () => (await details.boundingBox())!.height).toBe(0)
  expect(await card.evaluate((element) => element.getBoundingClientRect().top + window.scrollY)).toBeCloseTo(headerTop, 0)
  await expect(card.getByRole('button', { name: /choose craft for/ })).toHaveCount(0)

  await toggle.click()
  await expect(panel).toHaveCSS('animation-name', 'craft-disclosure-close')
  await expect(panel).toHaveAttribute('aria-hidden', 'true')
  await expect.poll(async () => (await panel.boundingBox())!.height).toBe(0)
  await toggle.click()
  await expect(card.getByRole('button', { name: 'Expand item set 1' })).toBeVisible()
  for (const width of [320, 375, 768]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await sheet.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
    await expect(card.getByRole('checkbox', { name: 'Include item set 1' })).toBeVisible()
  }
  await page.setViewportSize({ width: 375, height: 1000 })
  await sheet.screenshot({ path: 'test-results/crafting-sheet-compact-mobile.png', style: '.app-header { visibility: hidden !important; }' })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await toggle.click()
  await expect(panel).toHaveCSS('animation-name', 'none')
  await expect.poll(async () => (await panel.boundingBox())!.height).toBe(0)
})

test('reorders Latin item crafts and automatically uses two backspaces for lea to lab', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /english.*search crafts/ }).waitFor()
  await page.evaluate(() => {
    const workspace = JSON.parse(localStorage.getItem('mcsr.target-workspace.v1')!)
    const entry = workspace.entries.find((value: { targetIds: string[] }) => value.targetIds.includes('minecraft:golden_helmet'))
    entry.targetIds = ['minecraft:golden_helmet', 'minecraft:golden_pickaxe']
    entry.order = 0
    workspace.entries = [entry]
    localStorage.setItem('mcsr.target-workspace.v1', JSON.stringify(workspace))
  })
  await page.reload()
  await page.getByRole('button', { name: /^latin -/i }).click()
  const sheet = page.locator('.crafting-sheet')
  await sheet.getByRole('button', { name: /latin.*search crafts/i }).click()
  const card = sheet.getByRole('region', { name: 'item set 1', exact: true })
  await card.getByRole('button', { name: 'Expand item set 1' }).click()
  const helmetUp = card.getByRole('button', { name: /^Move Galea aurea up$/i })
  if (await helmetUp.isEnabled()) await helmetUp.click()
  const rows = card.locator('.crafting-sheet__individual-item')
  for (const [index, query] of ['lea', 'lab'].entries()) {
    await rows.nth(index).getByRole('button', { name: /choose craft for/ }).click()
    const choices = rows.nth(index).getByRole('region', { name: /Calculated crafts/ })
    await choices.getByRole('searchbox').fill(query)
    await choices.getByRole('button', { name: new RegExp(`^${query} \\d+ chars`) }).click()
  }
  const plan = card.locator('.crafting-sheet__plan')
  await expect(plan).toContainText('lea')
  await expect(plan.getByLabel('2 backspaces')).toBeVisible()
  await expect(plan.locator('.crafting-sheet__query-text').last()).toHaveText('ab')
  await expect(sheet.getByLabel('Total characters')).toHaveText('5')
  await expect(rows.nth(1).locator('.crafting-sheet__item-cost')).toContainText('2 chars')
  await expect(card.locator('.crafting-sheet__summary-item')).toHaveCount(2)
  // Labels are available through the icons, without taking up visible row space.
  await expect(card.getByText('Galea aurea', { exact: true })).toHaveCount(0)
  await rows.nth(1).getByRole('button', { name: /^Move .* up$/ }).click()
  await expect(plan.locator('.crafting-sheet__query-text').first()).toHaveText('lab')
  await expect(plan.locator('.crafting-sheet__query-text').last()).toHaveText('ea')
  await expect(card.locator('.crafting-sheet__query-preview').first()).toHaveText('lab')
  await page.reload()
  await sheet.getByRole('button', { name: /latin.*search crafts/i }).click()
  await card.getByRole('button', { name: 'Expand item set 1' }).click()
  await expect(plan.locator('.crafting-sheet__query-text').first()).toHaveText('lab')
  await rows.nth(0).getByRole('button', { name: /^Move .* down$/ }).click()
  await expect(plan.locator('.crafting-sheet__query-text').first()).toHaveText('lea')
  await expect(plan.getByLabel('2 backspaces')).toBeVisible()
  await sheet.screenshot({ path: 'test-results/crafting-sheet-latin-order.png', style: '.app-header { visibility: hidden !important; }' })
  await page.setViewportSize({ width: 375, height: 1000 })
  expect(await card.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await sheet.screenshot({ path: 'test-results/crafting-sheet-latin-order-mobile.png', style: '.app-header { visibility: hidden !important; }' })
  for (const index of [0, 1]) {
    await rows.nth(index).getByRole('button', { name: /choose craft for/ }).click()
    const choices = rows.nth(index).getByRole('region', { name: /Calculated crafts/ })
    await choices.getByRole('searchbox').fill('aurea')
    await choices.getByRole('button', { name: /^aurea \d+ chars/ }).click()
  }
  await expect(plan.locator('.crafting-sheet__query-text')).toHaveCount(1)
  await expect(plan.locator('.crafting-sheet__query-text')).toHaveText('aurea')
  await expect(sheet.getByLabel('Total characters')).toHaveText('5')
  await expect(rows.nth(1).locator('.crafting-sheet__item-cost')).toContainText('0 chars · 0 junk')
  await rows.nth(1).getByRole('button', { name: /choose craft for/ }).click()
  const splitChoices = rows.nth(1).getByRole('region', { name: /Calculated crafts/ })
  await splitChoices.getByRole('searchbox').fill('lab')
  await splitChoices.getByRole('button', { name: /^lab \d+ chars/ }).click()
  await expect(plan.locator('.crafting-sheet__query-text')).toHaveCount(2)
  await expect(plan.locator('.crafting-sheet__query-text').first()).toHaveText('aurea')
})
