import { expect, test } from '@playwright/test'

test('crafting sheet customizes bed and anchor, persists choices, and fits narrow screens', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /english.*search crafts/ }).waitFor()
  // Reuse the starter inventory, keeping exactly the two targets in this example.
  await page.evaluate(() => {
    const workspace = JSON.parse(localStorage.getItem('mcsr.target-workspace.v1')!)
    const entry = workspace.entries.find((value: { targetIds: string[] }) => value.targetIds.includes('minecraft:respawn_anchor'))
    entry.targetIds = ['minecraft:white_bed', 'minecraft:respawn_anchor']
    entry.order = 0
    workspace.entries = [entry]
    localStorage.setItem('mcsr.target-workspace.v1', JSON.stringify(workspace))
  })
  await page.reload()
  await page.getByRole('button', { name: /english.*search crafts/ }).click()
  const sheet = page.locator('.crafting-sheet')
  const card = sheet.getByRole('region', { name: 'item set 1', exact: true })
  await expect(card.getByText('Calculating crafts…')).toHaveCount(0)
  await card.getByRole('button', { name: 'Expand item set 1' }).click()
  await expect(card.locator('.crafting-sheet__plan')).toContainText('aw')
  await card.getByRole('button', { name: 'choose craft for item set 1' }).click()
  const combined = card.getByRole('region', { name: 'Calculated crafts for item set 1' })
  await combined.getByRole('searchbox').fill('be')
  const replaceCraft = combined.getByRole('button').filter({ hasText: 'Shift+Home' }).filter({ hasText: 'aw' }).filter({ hasText: 'be' }).first()
  await expect(replaceCraft).toBeVisible()
  await replaceCraft.click()
  await expect(card.locator('.crafting-sheet__plan')).toContainText('Shift+Home')
  await card.getByRole('button', { name: 'individual items', exact: true }).click()
  await card.getByRole('button', { name: 'choose craft for White Bed' }).click()
  const bedChoices = card.getByRole('region', { name: 'Calculated crafts for White Bed' })
  await bedChoices.getByRole('searchbox').fill('bed')
  await bedChoices.getByRole('button', { name: /^bed 3 chars/ }).click()
  await card.getByRole('button', { name: 'choose craft for Respawn Anchor' }).click()
  const anchorChoices = card.getByRole('region', { name: 'Calculated crafts for Respawn Anchor' })
  await anchorChoices.getByRole('searchbox').fill('aw')
  await anchorChoices.getByRole('button', { name: /^aw 2 chars/ }).click()
  await expect(card.locator('.crafting-sheet__plan')).toHaveText(/your sequencebedShift\+Homeaw/)
  await expect(sheet.getByLabel('Total characters')).toHaveText('5')
  await expect(sheet.getByLabel('Selected characters')).toHaveText('abdew')
  await expect(card.locator('.crafting-sheet__entry-metrics')).toContainText('+1 score')
  await page.reload()
  await page.getByRole('button', { name: /english.*search crafts/ }).click()
  await expect(card.getByLabel('Selected query for White Bed')).toHaveText('bed')
  await card.getByRole('button', { name: 'Expand item set 1' }).click()
  await expect(card.getByRole('button', { name: 'individual items', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(card.locator('.crafting-sheet__plan')).toHaveText(/your sequencebedShift\+Homeaw/)

  await page.evaluate(() => document.fonts.ready)
  const fonts = await sheet.evaluate((element) => ({
    query: getComputedStyle(element.querySelector('.crafting-sheet__query-text')!).fontFamily,
    metric: getComputedStyle(element.querySelector('.crafting-sheet__totals strong')!).fontFamily,
    key: getComputedStyle(element.querySelector('.crafting-sheet__key')!).fontFamily,
    title: getComputedStyle(element.querySelector('.crafting-sheet__title')!).fontFamily,
    subtitle: getComputedStyle(element.querySelector('.crafting-sheet__toggle-label')!).fontFamily,
  }))
  expect(fonts.query).toContain('Monocraft')
  expect(fonts.title).toContain('Coiny')
  expect(fonts.subtitle).toContain('Coiny')
  for (const font of [fonts.metric, fonts.key, fonts.title]) expect(font).not.toContain('Monocraft')

  await sheet.screenshot({ path: 'test-results/crafting-sheet-desktop.png' })
  for (const width of [320, 375, 768]) {
    await page.setViewportSize({ width, height: 1000 })
    await card.getByRole('button', { name: 'choose craft for White Bed' }).click()
    await expect(card.getByRole('searchbox')).toBeVisible()
    expect(await sheet.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
    expect(await card.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
    await card.getByRole('searchbox').press('Escape')
  }
  await page.setViewportSize({ width: 375, height: 1000 })
  await sheet.screenshot({ path: 'test-results/crafting-sheet-mobile.png', style: '.app-header { visibility: hidden !important; }' })
  await card.getByRole('checkbox', { name: 'Include item set 1' }).uncheck()
  await expect(sheet.getByLabel('Total characters')).toHaveText('0')
  await sheet.getByRole('button', { name: 'reset sheet' }).click()
  await expect(card.getByRole('checkbox', { name: 'Include item set 1' })).toBeChecked()
  await expect(card.getByRole('button', { name: 'combined craft', exact: true })).toHaveAttribute('aria-pressed', 'true')
})

test('crafting sheet has compact rows and animates open and closed like calculated rows', async ({ page }) => {
  await page.goto('/')
  const sheet = page.locator('.crafting-sheet')
  const toggle = sheet.getByRole('button', { name: /english.*search crafts/ })
  await toggle.click()
  const panel = sheet.locator(':scope > .crafting-sheet__details')
  await expect(panel).toHaveCSS('animation-name', 'craft-disclosure-open')
  await expect(panel).toHaveCSS('animation-duration', '0.42s')
  const card = sheet.getByRole('region', { name: 'item set 1', exact: true })
  await expect(card.getByRole('button', { name: 'Expand item set 1' })).toBeVisible()
  await expect(card.locator('.crafting-sheet__query-preview')).toBeVisible()
  await expect(card.locator('.crafting-sheet__query-preview')).toHaveCSS('border-top-width', '1px')
  await expect(card.locator('.item-icon').first()).toHaveCSS('width', '24px')
  await expect(card.locator('.item-icon').first()).toHaveCSS('height', '24px')
  await expect(sheet.locator('.crafting-sheet__entry-body')).toHaveCount(0)
  await expect(sheet.getByText('Updating crafting sheet… Totals include ready crafts.')).toHaveCount(0)
  await page.evaluate(() => document.fonts.ready)
  await sheet.screenshot({ path: 'test-results/crafting-sheet-compact-desktop.png', style: '.app-header { visibility: hidden !important; }' })
  const headerTop = await card.evaluate((element) => element.getBoundingClientRect().top + window.scrollY)
  await card.getByRole('button', { name: 'Expand item set 1' }).click()
  const details = card.locator('.crafting-sheet__details')
  await expect(card.getByRole('button', { name: 'choose craft for item set 1' })).toBeVisible()
  await expect(details).toHaveCSS('animation-name', 'craft-disclosure-open')
  await card.getByRole('button', { name: 'Collapse item set 1' }).click()
  await expect(details).toHaveCSS('animation-name', 'craft-disclosure-close')
  await expect(details).toHaveAttribute('inert', '')
  await expect.poll(async () => (await details.boundingBox())!.height).toBe(0)
  expect(await card.evaluate((element) => element.getBoundingClientRect().top + window.scrollY)).toBeCloseTo(headerTop, 0)
  await expect(card.getByRole('button', { name: 'choose craft for item set 1' })).toHaveCount(0)

  await toggle.click()
  await expect(panel).toHaveCSS('animation-name', 'craft-disclosure-close')
  await expect(panel).toHaveAttribute('aria-hidden', 'true')
  await expect.poll(async () => (await panel.boundingBox())!.height).toBe(0)
  await toggle.click()
  await expect(card.getByRole('button', { name: 'Expand item set 1' })).toBeVisible()
  for (const width of [320, 375, 768]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await sheet.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
    await expect(card.getByRole('checkbox', { name: 'Include item set 1' })).toBeVisible()
  }
  await page.setViewportSize({ width: 375, height: 1000 })
  await sheet.screenshot({ path: 'test-results/crafting-sheet-compact-mobile.png', style: '.app-header { visibility: hidden !important; }' })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await toggle.click()
  await expect(panel).toHaveCSS('animation-name', 'none')
  await expect.poll(async () => (await panel.boundingBox())!.height).toBe(0)
})
