import { expect, test } from '@playwright/test'

test('saves custom keys, rejects duplicates, and translates craft playback after reload', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'crafting sheet', exact: true }).click()
  const entry = page.getByRole('region', { name: 'item set 1', exact: true })
  await entry.getByRole('button', { name: 'Expand item set 1' }).click()
  const firstCharacter = (await entry.locator('.crafting-sheet__plan .crafting-sheet__query-text').first().innerText())[0].replace('_', ' ')
  await page.getByRole('button', { name: 'settings', exact: true }).click()
  await page.getByRole('button', { name: 'Rebind x', exact: true }).click()
  await page.getByRole('textbox', { name: 'New output for x' }).fill(firstCharacter)
  await page.getByRole('button', { name: 'Rebind c', exact: true }).click()
  await page.getByRole('textbox', { name: 'New output for c' }).fill(firstCharacter)
  await expect(page.getByRole('button', { name: 'save settings' })).toBeDisabled()
  await expect(page.getByRole('alert')).toContainText('Duplicate custom bindings')
  await page.locator('[data-code="KeyC"]').click()
  await page.getByRole('button', { name: 'restore key', exact: true }).click()
  await page.getByRole('button', { name: 'Bind chat key' }).click()
  await page.getByRole('button', { name: 'Rebind mouse 4', exact: true }).click()
  await page.getByRole('button', { name: 'Bind backspace', exact: true }).click()
  await page.getByRole('textbox', { name: 'New binding for backspace' }).press('Backspace')
  await expect(page.locator('[data-code="KeyX"]')).toHaveCSS('background-color', 'rgb(196, 232, 207)')
  await page.getByRole('group', { name: 'keyboard inputs', exact: true }).screenshot({ path: 'test-results/keyboard-settings.png' })
  await page.getByRole('button', { name: 'save settings' }).click()
  await page.reload()
  await page.getByRole('button', { name: 'crafting sheet', exact: true }).click()
  await entry.getByRole('button', { name: 'Expand item set 1' }).click()
  await expect(entry.locator('.keyboard-playback__token').first()).toHaveText('x')
  await expect(entry.getByRole('group', { name: '75% keyboard and five-button mouse' })).toBeVisible()
  await page.evaluate(() => { document.documentElement.dataset.theme = 'dark' })
  const fadedText = await entry.locator('.keyboard-visual__key:has(.keyboard-visual__light) .keyboard-visual__label').evaluate((element) => {
    element.getAnimations().forEach((animation) => animation.finish())
    const expected = document.createElement('span')
    expected.style.color = 'var(--text)'
    element.parentElement!.append(expected)
    const colors = { actual: getComputedStyle(element).color, expected: getComputedStyle(expected).color }
    expected.remove()
    return colors
  })
  expect(fadedText.actual).toBe(fadedText.expected)
  await entry.getByRole('button', { name: 'pause sequence' }).click()
  await entry.screenshot({ path: 'test-results/keyboard-playback.png' })
  expect(await entry.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
})

test('detects mapped controls and offers independent language characters with the revised layout', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'settings', exact: true }).click()
  await page.getByRole('button', { name: 'Rebind r', exact: true }).click()
  await page.getByRole('textbox', { name: 'New output for r' }).press('Backspace')
  await expect(page.getByRole('button', { name: 'Bind backspace', exact: true })).toHaveText('r (detected)')
  await page.getByRole('combobox', { name: 'Keyboard character language' }).fill('norwegian')
  await page.getByRole('option', { name: /norwegian bokmål/i }).click()
  await expect(page.getByLabel('Copyable special characters')).toHaveValue(/æ.*ø/)
  const mouse = page.locator('.keyboard-visual__mouse')
  const fourth = await mouse.locator('[data-code="Mouse3"]').boundingBox()
  const fifth = await mouse.locator('[data-code="Mouse4"]').boundingBox()
  const left = await mouse.locator('[data-code="Mouse0"]').boundingBox()
  expect(fourth!.x).toBe(fifth!.x)
  expect(fourth!.x).toBe(left!.x)
  expect(fourth!.y).toBeGreaterThanOrEqual(left!.y + left!.height)
  expect(fifth!.y).toBeGreaterThanOrEqual(fourth!.y + fourth!.height)
  const width = await page.getByRole('textbox', { name: 'additional character penalty', exact: true }).evaluate((element) => {
    const styles = getComputedStyle(element)
    return { width: Number.parseFloat(styles.width), font: Number.parseFloat(styles.fontSize) }
  })
  expect(width.width).toBeGreaterThan(width.font * 2)
  await page.getByRole('group', { name: 'keyboard inputs', exact: true }).screenshot({ path: 'test-results/keyboard-settings-updated.png', style: '.app-header { visibility: hidden !important; }' })
  await page.getByRole('button', { name: 'save settings' }).click()
  await page.reload()
  await page.getByRole('button', { name: 'crafting sheet', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Back to english (us) crafts' })).toBeVisible()
})

test('supports tapping keys on a narrow touch screen without overflowing settings', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true })
  const page = await context.newPage()
  await page.goto('/')
  await page.getByRole('button', { name: 'settings', exact: true }).tap()
  await page.getByRole('button', { name: 'Rebind x', exact: true }).tap()
  await page.getByRole('textbox', { name: 'New output for x' }).fill('s')
  await expect(page.getByRole('button', { name: 'Rebind x → s', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'save settings' }).tap()
  await expect(page.getByRole('status')).toHaveText('settings saved')
  expect(await page.locator('.settings-page').evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await context.close()
})
