import { expect, test } from '@playwright/test'

test('manual binds override displaced physical keys and persist on the keyboard diagram', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'settings', exact: true }).click()
  for (const [key, output] of [['x', 'i'], ['f', 't']]) {
    await page.getByRole('button', { name: `Rebind ${key}`, exact: true }).click()
    await page.getByRole('textbox', { name: `New output for ${key}` }).press(output)
  }
  for (const [control, key] of [['home', 'i'], ['shift', 'CapsLock'], ['chat key', 't']]) {
    await page.getByRole('button', { name: `Bind ${control}`, exact: true }).click()
    await page.getByRole('textbox', { name: `New binding for ${control}` }).press(key)
    await expect(page.getByRole('button', { name: `Bind ${control}`, exact: true })).toHaveAttribute('aria-invalid', 'false')
  }
  await expect(page.locator('[data-code="KeyI"]')).toHaveText('hm')
  await expect(page.locator('[data-code="CapsLock"]')).toHaveText('SH')
  await expect(page.locator('[data-code="KeyT"]')).toHaveText('CH')
  await page.getByRole('button', { name: 'save settings' }).click()
  await page.reload()
  await page.getByRole('button', { name: 'settings', exact: true }).click()
  await expect(page.locator('[data-code="KeyI"]')).toHaveText('hm')
  await expect(page.locator('[data-code="KeyI"]')).not.toHaveClass(/conflict/)
})

test('keeps header controls the same height and moves playback guidance into craft-sheet help', async ({ page }) => {
  await page.goto('/')
  for (const width of [1440, 1152, 1000, 390, 320]) {
    await page.setViewportSize({ width, height: 1000 })
    const nav = await page.getByRole('button', { name: 'settings', exact: true }).boundingBox()
    for (const name of ['Help for search crafting', 'Choose color theme']) {
      const button = await page.getByRole('button', { name, exact: true }).boundingBox()
      expect(button!.height).toBeCloseTo(nav!.height, 0)
    }
    const help = page.getByRole('button', { name: 'Help for search crafting', exact: true })
    await expect(help).toHaveCSS('font-family', 'Monocraft, monospace')
    expect(await help.evaluate((button) => {
      const range = document.createRange()
      range.selectNodeContents(button)
      const text = range.getBoundingClientRect()
      const bounds = button.getBoundingClientRect()
      return text.top >= bounds.top && text.bottom <= bounds.bottom
        && text.left >= bounds.left && text.right <= bounds.right
    })).toBe(true)
    await page.locator('.app-header').screenshot({ path: `test-results/header-controls-${width}.png` })
  }
  await page.getByRole('button', { name: 'crafting sheet', exact: true }).click()
  await page.getByRole('button', { name: 'Expand item set 1' }).click()
  const playback = page.locator('.keyboard-playback').first()
  await expect(playback.locator('.keyboard-playback__actions small')).toHaveCount(0)
  await expect(playback.locator('.keyboard-visual__label')).toHaveCount(0)
  await expect(playback.locator('.keyboard-visual__key').first()).toHaveAttribute('aria-label', 'esc')
  await page.getByRole('button', { name: 'Help for crafting sheet' }).click()
  const tutorial = page.getByRole('dialog')
  await expect(tutorial.getByRole('heading', { name: 'Your craft sheet' })).toBeVisible()
  await tutorial.getByRole('button', { name: 'next', exact: true }).click()
  await expect(tutorial).toContainText('pastel blue')
  await tutorial.getByRole('button', { name: 'next', exact: true }).click()
  await expect(tutorial).toContainText('Unmapped characters')
  await tutorial.getByRole('button', { name: 'next', exact: true }).click()
  await expect(tutorial).toContainText('Pause')
  await tutorial.getByRole('button', { name: 'finish', exact: true }).click()
  await expect(tutorial).toHaveCount(0)
})

test('saves custom keys, rejects duplicates, and translates craft playback after reload', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'crafting sheet', exact: true }).click()
  const entry = page.getByRole('region', { name: 'item set 1', exact: true })
  await entry.getByRole('button', { name: 'Expand item set 1' }).click()
  const firstCharacter = (await entry.locator('.crafting-sheet__plan .crafting-sheet__query-text').first().innerText())[0].replace('_', ' ')
  await page.getByRole('button', { name: 'settings', exact: true }).click()
  await page.getByRole('button', { name: 'Rebind x', exact: true }).click()
  await page.getByRole('textbox', { name: 'New output for x' }).fill(firstCharacter)
  await page.getByRole('button', { name: 'Rebind c', exact: true }).click()
  await page.getByRole('textbox', { name: 'New output for c' }).fill(firstCharacter)
  await expect(page.getByRole('button', { name: 'save settings' })).toBeDisabled()
  await expect(page.getByRole('alert')).toContainText('Duplicate custom bindings')
  await page.locator('[data-code="KeyC"]').click()
  await page.getByRole('button', { name: 'restore key', exact: true }).click()
  await page.getByRole('button', { name: 'Bind chat key' }).click()
  await page.getByRole('button', { name: 'Rebind mouse 4', exact: true }).click()
  await page.getByRole('button', { name: 'Bind backspace', exact: true }).click()
  await page.getByRole('textbox', { name: 'New binding for backspace' }).press('Backspace')
  await expect(page.locator('[data-code="KeyX"]')).toHaveCSS('background-color', 'rgb(196, 232, 207)')
  await page.getByRole('group', { name: 'keyboard inputs', exact: true }).screenshot({ path: 'test-results/keyboard-settings.png' })
  await page.getByRole('button', { name: 'save settings' }).click()
  await page.reload()
  await page.getByRole('button', { name: 'crafting sheet', exact: true }).click()
  await entry.getByRole('button', { name: 'Expand item set 1' }).click()
  await expect(entry.locator('.keyboard-playback__token').first()).toHaveText('x')
  await expect(entry.getByRole('group', { name: '75% keyboard and five-button mouse' })).toBeVisible()
  await expect(entry.locator('.keyboard-visual__label')).toHaveCount(0)
  await expect(entry.locator('.keyboard-visual__light').first()).toHaveCSS('animation-duration', '0.464s')
  await entry.getByRole('button', { name: 'pause sequence' }).click()
  await entry.screenshot({ path: 'test-results/keyboard-playback.png' })
  expect(await entry.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
})

test('detects mapped controls and offers independent language characters with the revised layout', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'settings', exact: true }).click()
  await page.getByRole('button', { name: 'Rebind r', exact: true }).click()
  await page.getByRole('textbox', { name: 'New output for r' }).press('Backspace')
  await expect(page.getByRole('button', { name: 'Bind backspace', exact: true })).toHaveText('r')
  await page.getByRole('button', { name: 'Clear backspace', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Rebind r', exact: true })).toHaveText('r')
  await expect(page.getByRole('button', { name: 'Bind backspace', exact: true })).toHaveText('unbound')
  await page.getByRole('button', { name: 'Rebind r', exact: true }).click()
  await expect(page.locator('.keyboard-editor__capture + .keyboard-editor__controls')).toHaveCount(1)
  await page.getByRole('textbox', { name: 'New output for r' }).press('Backspace')
  await page.getByRole('button', { name: 'Bind backspace', exact: true }).click()
  await page.getByRole('button', { name: 'clear binding', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Rebind r', exact: true })).toHaveText('r')
  await page.getByRole('combobox', { name: 'Keyboard character language' }).fill('norwegian')
  await page.getByRole('option', { name: /norwegian bokmål/i }).click()
  await expect(page.getByLabel('Copyable special characters')).toHaveValue(/æ.*ø/)
  const mouse = page.locator('.keyboard-visual__mouse')
  const fourth = await mouse.locator('[data-code="Mouse3"]').boundingBox()
  const fifth = await mouse.locator('[data-code="Mouse4"]').boundingBox()
  const left = await mouse.locator('[data-code="Mouse0"]').boundingBox()
  expect(fourth!.x).toBe(fifth!.x)
  expect(fourth!.x).toBe(left!.x)
  expect(fourth!.y).toBeGreaterThanOrEqual(left!.y + left!.height)
  expect(fifth!.y).toBeGreaterThanOrEqual(fourth!.y + fourth!.height)
  const width = await page.getByRole('textbox', { name: 'additional character penalty', exact: true }).evaluate((element) => {
    const styles = getComputedStyle(element)
    return { width: Number.parseFloat(styles.width), font: Number.parseFloat(styles.fontSize) }
  })
  expect(width.width).toBeGreaterThan(width.font * 2)
  await page.getByRole('group', { name: 'keyboard inputs', exact: true }).screenshot({ path: 'test-results/keyboard-settings-updated.png', style: '.app-header { visibility: hidden !important; }' })
  await page.getByRole('button', { name: 'save settings' }).click()
  await page.reload()
  await page.getByRole('button', { name: 'crafting sheet', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Back to english (us) crafts' })).toBeVisible()
})

test('supports tapping keys on a narrow touch screen without overflowing settings', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true })
  const page = await context.newPage()
  await page.goto('/')
  const languageSearch = page.getByRole('searchbox', { name: 'Search languages' })
  await expect(languageSearch).toHaveCSS('font-size', '16px')
  await languageSearch.tap()
  await languageSearch.fill('ovdals')
  await expect(page.getByRole('button', { name: /elfdalian - övdalska/ })).toBeVisible()
  expect(await page.evaluate(() => window.visualViewport?.scale)).toBe(1)
  await page.getByRole('button', { name: 'settings', exact: true }).tap()
  await expect(page.getByRole('combobox', { name: 'Keyboard character language' })).toHaveCSS('font-size', '16px')
  await page.getByRole('button', { name: 'Rebind x', exact: true }).tap()
  await page.getByRole('textbox', { name: 'New output for x' }).fill('s')
  await expect(page.getByRole('button', { name: 'Rebind x → s', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'save settings' }).tap()
  await expect(page.getByRole('status')).toHaveText('settings saved')
  expect(await page.locator('.settings-page').evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await context.close()
})
